---
production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
development:
  clients:
    default:
      database: rails_mongodb_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: rails_mongodb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
